opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_xctest_method
#  - identical_operands (not available yet)
#  - legacy_random (not available yet)
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - operator_usage_whitespace
  - override_in_extension
#  - toggle_bool (not available yet)
  - unneeded_parentheses_in_closure_argument
#  - unused_import (not available yet)
#  - unused_private_declaration (not available yet)
  - yoda_condition

disabled_rules:
  - line_length
  - file_length
  - function_body_length
  - function_parameter_count
  - type_body_length

identifier_name:
  min_length:
    warning: 1
    error: 1

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
